### ISSUE TITLE
How can I run it?

### ISSUE THREAD

**Issue by lvyanan525** [krentzd/napari-clemreg#21]

**Comment by lvyanan525** [comment]
when I run "python run_registration.py", there is nothing happened

**Comment by krentzd** [comment]
Hi, you need to install napari with `pip install "napari[all]"` and then the plugin with `pip install napari-clemreg`. Once both of these are installed, you can open napari from the terminal by simply typing `napari`. Then, you can select the napari-clemreg plugin from the plugin menu to run it. Hope this helps!
