### ISSUE TITLE
BCPD error 

### ISSUE THREAD

**Issue by johannesmaxkappel** [krentzd/napari-clemreg#23]
Hi, I ran BCPD in napari following segmentation and point cloud sampling for two image stacks and received the following error. It does not occur when using Affine or Rigid CPD on the same data. Any idea what is going on? The error occurs after registration, so during image warping.

> TypeError                                 Traceback (most recent call last)
> File ~\AppData\Local\anaconda3\envs\clemreg_env\lib\site-packages\napari_clemreg\widgets\registration_warping.py:146, in registration_warping_widget.<locals>._add_data(return_value=([<Image layer 'substack_confocal2_warped'>], <class 'numpy.ndarray'> (1092, 3) float64))
>     144 def _add_data(return_value):
>     145     image_layers, points_layer = return_value
> --> 146     viewer.add_layer(points_layer)
>         points_layer = <class 'numpy.ndarray'> (1092, 3) float64
>         viewer = Viewer(camera=Camera(center=(50.0, 92.0, 90.5), zoom=3.265173412240934, angles=(9.067953538531793, -1.5414049032767563, 90.79352160009522), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(53.07563540954868, 126.3104796784496, -6.1279843342897635), scaled=True, size=10, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=3, ndisplay=3, last_used=0, range=((0.0, 101.0, 1.0), (0.0, 185.0, 1.0), (0.0, 182.0, 1.0)), current_step=(16, 92, 90), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>], help='use <1> for activate the label eraser, use <2> for activate the paint brush, use <3> for activate the fill bucket, use <4> for pick mode', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001BDEC6630D0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})
>     148     layers = []
>     149     for image_layer in image_layers:
> 
> File ~\AppData\Local\anaconda3\envs\clemreg_env\lib\site-packages\napari\utils\_proxies.py:192, in CallablePublicOnlyProxy.__call__(self=<bound method ViewerModel.add_layer of Viewer(ca...use_drag_gen={}, _mouse_wheel_gen={}, keymap={})>, *args=[<class 'numpy.ndarray'> (1092, 3) float64], **kwargs={})
>     184 args = [
>     185     arg.__wrapped__ if isinstance(arg, PublicOnlyProxy) else arg
>     186     for arg in args
>     187 ]
>     188 kwargs = {
>     189     k: v.__wrapped__ if isinstance(v, PublicOnlyProxy) else v
>     190     for k, v in kwargs.items()
>     191 }
> --> 192 return self.create(self.__wrapped__(*args, **kwargs))
>         args = [<class 'numpy.ndarray'> (1092, 3) float64]
>         kwargs = {}
>         self = <bound method ViewerModel.add_layer of Viewer(camera=Camera(center=(50.0, 92.0, 90.5), zoom=3.265173412240934, angles=(9.067953538531793, -1.5414049032767563, 90.79352160009522), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(53.07563540954868, 126.3104796784496, -6.1279843342897635), scaled=True, size=10, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=3, ndisplay=3, last_used=0, range=((0.0, 101.0, 1.0), (0.0, 185.0, 1.0), (0.0, 182.0, 1.0)), current_step=(16, 92, 90), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>], help='use <1> for activate the label eraser, use <2> for activate the paint brush, use <3> for activate the fill bucket, use <4> for pick mode', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001BDEC6630D0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})>
> 
> File ~\AppData\Local\anaconda3\envs\clemreg_env\lib\site-packages\napari\components\viewer_model.py:652, in ViewerModel.add_layer(self=Viewer(camera=Camera(center=(50.0, 92.0, 90.5), ...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), layer=<class 'numpy.ndarray'> (1092, 3) float64)
>     636 """Add a layer to the viewer.
>     637
>     638 Parameters
>    (...)
>     646     The layer that was added (same as input).
>     647 """
>     648 # Adding additional functionality inside `add_layer`
>     649 # should be avoided to keep full functionality
>     650 # from adding a layer through the `layers.append`
>     651 # method
> --> 652 self.layers.append(layer)
>         layer = <class 'numpy.ndarray'> (1092, 3) float64
>         self.layers = [<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>]
>         self = Viewer(camera=Camera(center=(50.0, 92.0, 90.5), zoom=3.265173412240934, angles=(9.067953538531793, -1.5414049032767563, 90.79352160009522), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(53.07563540954868, 126.3104796784496, -6.1279843342897635), scaled=True, size=10, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=3, ndisplay=3, last_used=0, range=((0.0, 101.0, 1.0), (0.0, 185.0, 1.0), (0.0, 182.0, 1.0)), current_step=(16, 92, 90), order=(0, 1, 2), axis_labels=('0', '1', '2')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>], help='use <1> for activate the label eraser, use <2> for activate the paint brush, use <3> for activate the fill bucket, use <4> for pick mode', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001BDEC6630D0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})
>     653 return layer
> 
> File ~\AppData\Local\anaconda3\envs\clemreg_env\lib\_collections_abc.py:1073, in MutableSequence.append(self=[<Image layer 'substack_confocal2' at 0x1bdfa42e...ints layer 'Fixed_point_cloud' at 0x1bd91be3e80>], value=<class 'numpy.ndarray'> (1092, 3) float64)
>    1071 def append(self, value):
>    1072     'S.append(value) -- append value to the end of the sequence'
> -> 1073     self.insert(len(self), value)
>         value = <class 'numpy.ndarray'> (1092, 3) float64
>         self = [<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>]
> 
> File ~\AppData\Local\anaconda3\envs\clemreg_env\lib\site-packages\napari\components\layerlist.py:162, in LayerList.insert(self=[<Image layer 'substack_confocal2' at 0x1bdfa42e...ints layer 'Fixed_point_cloud' at 0x1bd91be3e80>], index=6, value=<class 'numpy.ndarray'> (1092, 3) float64)
>     160 def insert(self, index: int, value: Layer):
>     161     """Insert ``value`` before index."""
> --> 162     (value,) = self._ensure_unique((value,))
>         (value,) = (<class 'numpy.ndarray'> (1092, 3) float64,)
>         value = <class 'numpy.ndarray'> (1092, 3) float64
>         self = [<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>]
>     163     new_layer = self._type_check(value)
>     164     new_layer.name = self._coerce_name(new_layer.name)
> 
> File ~\AppData\Local\anaconda3\envs\clemreg_env\lib\site-packages\napari\components\layerlist.py:142, in LayerList._ensure_unique(self=[<Image layer 'substack_confocal2' at 0x1bdfa42e...ints layer 'Fixed_point_cloud' at 0x1bd91be3e80>], values=(<class 'numpy.ndarray'> (1092, 3) float64,), allow=())
>     140 values = tuple(values) if isinstance(values, Iterable) else (values,)
>     141 for v in values:
> --> 142     if v in bad:
>         bad = {<Image layer 'substack_confocal2' at 0x1bdfa42ed00>, <Image layer 'substack_diff2' at 0x1bd803da160>, <Points layer 'Fixed_point_cloud' at 0x1bd91be3e80>, <Labels layer 'FM_segmentation' at 0x1bd8f209a90>, <Labels layer 'FM_segmentation [1]' at 0x1bd804b9dc0>, <Points layer 'Moving_point_cloud' at 0x1bd832e55e0>}
>         v = <class 'numpy.ndarray'> (1092, 3) float64
>     143         raise ValueError(
>     144             trans._(
>     145                 "Layer '{v}' is already present in layer list",
>    (...)
>     148             )
>     149         )
>     150 return values
> 
> TypeError: unhashable type: 'numpy.ndarray'
>

**Comment by krentzd** [comment]
Hi, thanks for reaching out! It looks like there's an error when adding the warped layer(s) to the napari viewer. Did you link various layers of the moving image before running the workflow?

**Comment by johannesmaxkappel** [comment]
Hi! Thanks a lot for the super fast response. I did not link layers, at least not knowingly. I did have multiple layers visible at once when running the registration though if that is what you mean.

**Comment by krentzd** [comment]
Hi, there was indeed a bug that I suspect might have caused the error. I have now addressed it and pushed the changes to a new branch (`bcpd-bug-fixes`). To test if this fixes your error you can re-install the plugin with `pip install git+https://github.com/krentzd/napari-clemreg.git@bcpd-bug-fixes`.

Please let me know how it goes and thanks a lot for raising the issue!
